  [31morigin/Chore/JIRA[m
  [31morigin/HEAD[m -> origin/main
  [31morigin/QUOS-22-Resistration[m
  [31morigin/QUOS-23-CardBenefits[m
  [31morigin/QUOS-24-Stock[m
  [31morigin/QUOS-25-Feat/getBenefitChangeDate[m
  [31morigin/QUOS-26-Feat/checkBenefitValidity[m
  [31morigin/QUOS-27-Feat/updateBenefit[m
  [31morigin/QUOS-28-Feat/reserveBenefit[m
  [31morigin/QUOS-31-Feat/StockWishList[m
  [31morigin/QUOS-32-Lotto[m
  [31morigin/QUOS-34-Feat/participant2[m
  [31morigin/QUOS-35-Feat/stockSearch[m
  [31morigin/QUOS-36-Feat/participant1[m
  [31morigin/QUOS-37-Feat/viewCardBenefits[m
  [31morigin/QUOS-38-Feat/secondaryAuthCode[m
  [31morigin/dev[m
  [31morigin/main[m
  [31morigin/secondary[m
