spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379

    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200

  jmx:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration

logging:
  level:
    root: INFO
    sun.rmi: WARN
    javax.management: WARN
    jdk.internal.httpclient: WARN
    org.springframework.web.client.RestClient: INFO  # RestClient 관련 로그만 보고 싶을 때

appkey: ${OPENAPI_APPKEY}
appsecret: ${OPENAPI_APPSECRET}

aws:
  accessKeyId: ${ACCESS_KEY_ID}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${S3_BUCKET_NAME}