spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
aws:
  accessKeyId: ${ACCESS_KEY_ID}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${S3_BUCKET_NAME}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000

  refresh:
    expiration: 259200000

server:
  servlet:
    session:
      cookie:
        same-site: none

aes:
  secret:
    key: ${AES_SECRET_KEY}
    salt: ${AES_SECRET_SALT}